# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s67-0kFzmq4O83yW0rzd34vODcTUJbmu
"""

#ex1
mylist=[input()]
x=len(mylist)
a=0

while a<x:
  z=1
  y=mylist[a]
  z=y*z
  a=a+1 
print(z)

#ex2
def min(t):
  min1=t[0]
  for element in t:
    if min1[1]>element[1]:
      min1=element
  return min1 

t=[(2, 5), (1, 2), (4, 4), (2, 3), (2, 1)]
x=len(t)
a=0
t2=[]

while a<x :
 min1=min(t)
 t2.append(min1)
 t.remove(min1)
 a=a+1
print(t2)

#ex3
d1 = {'a': 100, 'b': 200, 'c':300}
d2 = {'a': 300, 'b': 200, 'd':400}
d3=dict()
for i_d1 in d1:
  if i_d1 in d2.keys():
    d3[i_d1]=d1[i_d1]+d2[i_d1]
  else:
    d3[i_d1]=d1[i_d1]
for i_d2 in  d2:
  if i_d2 not in d1.keys():
    d3[i_d2]=d2[i_d2]


print(d3)

#ex4
n=int(input()) 
d=dict()
a=1
while a<=n :
  d[a]=a*a
  a=a+1
print(d)

#ex5
def max(t):
  max1=t[0]
  for element in t:
    if max1[1]<element[1]:
      max1=element
  return max1 

t=[('item1', '12.20'), ('item2', '15.10'), ('item3', '24.5')]
x=len(t)
a=0
t2=[]

while a<x :
 max1=max(t)
 t2.append(max1)
 t.remove(max1)
 a=a+1
print(t2)